# Generated by Django 5.1.15 on 2026-10-09 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã bộ môn (ARC, STR, MEP...)')),
                ('name', models.CharField(max_length=100, verbose_name='Tên bộ môn')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Bộ môn',
                'verbose_name_plural': 'Danh mục Bộ môn',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên luồng công việc')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
            ],
            options={
                'verbose_name': 'Luồng công việc',
                'verbose_name_plural': 'Danh mục Luồng công việc',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Key file trên S3 (images/YYYY/MM/<uuid>.<ext>)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tải lên')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tải lên')),
            ],
            options={
                'verbose_name': 'Hình ảnh đính kèm',
                'verbose_name_plural': 'Thư viện Hình ảnh S3',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Ví dụ: ARC-Model-01, STR-Coord-02', max_length=50, unique=True, verbose_name='Mã quy trình')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề quy trình')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content_type', models.CharField(choices=[('MARKDOWN', 'Markdown'), ('HTML', 'HTML Độc lập (1 file)')], default='MARKDOWN', max_length=20, verbose_name='Định dạng nội dung')),
                ('content_markdown', models.TextField(blank=True, default='', verbose_name='Nội dung Markdown')),
                ('html_file', models.CharField(blank=True, default='', max_length=255, verbose_name='Key file HTML trên S3 (html/<uuid>.html)')),
                ('search_text', models.TextField(blank=True, default='', verbose_name='Text thuần tìm kiếm (tự sinh)')),
                ('status', models.CharField(choices=[('DRAFT', 'Bản thảo (Draft)'), ('PUBLISHED', 'Đã xuất bản (Published)')], default='DRAFT', max_length=20, verbose_name='Trạng thái')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xuất bản')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật gần nhất')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Tác giả')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='docs.department', verbose_name='Bộ môn')),
                ('images', models.ManyToManyField(blank=True, related_name='documents', to='docs.imageattachment', verbose_name='Hình ảnh liên kết')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='docs.workflow', verbose_name='Luồng công việc')),
            ],
            options={
                'verbose_name': 'Tài liệu Quy trình',
                'verbose_name_plural': 'Danh mục Tài liệu Quy trình',
                'ordering': ['department', 'code'],
            },
        ),
    ]
