# Generated by Django 5.1.15 on 2026-10-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_html',
            field=models.TextField(blank=True, default='', verbose_name='Nội dung HTML (lưu trực tiếp trong CSDL)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='html_file',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Đường dẫn file HTML (tùy chọn)'),
        ),
    ]
